# Generated by Django 5.2.6 on 2026-10-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "scheduled",
                            "checked_in",
                            "in_progress",
                            "completed",
                            "cancelled",
                            "no_show",
                        ],
                    )
                ),
                name="appointment_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispensing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["partial", "completed", "cancelled"])
                ),
                name="dispensing_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "issued", "voided"])),
                name="invoice_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="pharmacyreturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "approved", "rejected"])),
                name="pharmacy_return_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="pharmacysale",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "issued", "voided"])),
                name="pharmacy_sale_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="prescription",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "issued", "cancelled"])),
                name="prescription_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "approved", "rejected", "issued"])
                ),
                name="refund_status_valid",
            ),
        ),
    ]
