# Generated by Django 5.2.6 on 2026-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_appointment_appointment_status_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoiceline",
            name="invoice_line_amounts_nonnegative",
        ),
        migrations.RemoveConstraint(
            model_name="service",
            name="service_charge_nonnegative",
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="current_charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_price__gte", 0),
                    models.Q(
                        ("tax_rate__isnull", True),
                        ("tax_rate__gte", 0),
                        _connector="OR",
                    ),
                    ("discount_amount__gte", 0),
                    ("line_total__gte", 0),
                ),
                name="invoice_line_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_charge__isnull", True),
                    ("current_charge__gte", 0),
                    _connector="OR",
                ),
                name="service_charge_nonnegative",
            ),
        ),
    ]
