# Generated by Django 5.2.6 on 2026-10-03 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_invoiceline_invoice_line_amounts_nonnegative_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adjustment",
            options={
                "permissions": [
                    ("approve_adjustment", "Can approve a financial adjustment")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"permissions": [("void_invoice", "Can void an issued invoice")]},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={
                "permissions": [
                    ("view_all_patient_records", "Can view all patient records")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="refund",
            options={"permissions": [("approve_refund", "Can approve a refund")]},
        ),
    ]
