# Generated by Django 5.2.6 on 2026-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_adjustment_options_alter_invoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="no_show_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["scheduled", "checked_in", "in_progress"])
                ),
                fields=("doctor", "scheduled_at"),
                name="appointment_doctor_active_slot_unique",
            ),
        ),
    ]
