# Generated by Django 5.2.6 on 2026-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_payment_receipt_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicinebatch",
            options={"permissions": [("adjust_stock", "Can adjust medicine stock")]},
        ),
        migrations.RemoveConstraint(
            model_name="medicinebatch",
            name="batch_on_hand_valid",
        ),
        migrations.AddField(
            model_name="medicinebatch",
            name="is_quarantined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="medicinebatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_on_hand__gte", 0)),
                name="batch_on_hand_valid",
            ),
        ),
    ]
