# Generated by Django 5.2.6 on 2026-10-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_medicinebatch_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispensing",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispensing",
                to="core.invoice",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_otc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pharmacyreturn",
            name="request_key",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pharmacysale",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pharmacy_sale",
                to="core.invoice",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="pharmacy_return",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund",
                to="core.pharmacyreturn",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="request_key",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="core.patient",
            ),
        ),
    ]
