# Generated by Django 5.2.6 on 2026-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_dispensing_invoice_medicine_is_otc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="follow_up_note",
            field=models.TextField(blank=True),
        ),
    ]
