# Generated by Django 5.2.6 on 2026-10-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('prescription', 'Scanned Prescription'), ('lab_report', 'Lab / Pathology Report'), ('radiology', 'Radiology / X-Ray / Scan'), ('discharge', 'Discharge Summary'), ('other', 'Other Clinical Document')], default='prescription', max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='core.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
