# Generated by Django 5.2.6 on 2026-10-05 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed_number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Cleaning / Maintenance')], default='available', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('general', 'General Ward'), ('semi_private', 'Semi-Private Ward'), ('private', 'Private Deluxe Room'), ('icu', 'Intensive Care Unit (ICU)'), ('ccu', 'Critical Care Unit (CCU)'), ('emergency', 'Emergency / Trauma Ward')], default='general', max_length=24)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('admitted', 'Currently Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('lama', 'Left Against Medical Advice (LAMA)')], default='admitted', max_length=16)),
                ('admission_reason', models.TextField()),
                ('is_mlc', models.BooleanField(default=False, verbose_name='Medico-Legal Case (MLC)')),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('discharge_condition', models.CharField(blank=True, max_length=120)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_recorded', to='core.staffprofile')),
                ('admitting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_handled', to='core.staffprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='core.patient')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='core.bed')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InpatientDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank/UPI UTR or Card Auth Code', max_length=100)),
                ('deposited_by_name', models.CharField(blank=True, help_text='Family / Attendant name', max_length=160)),
                ('deposited_by_phone', models.CharField(blank=True, max_length=32)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.admission')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentmethod')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_deposits_collected', to='core.staffprofile')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='core.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
